### ISSUE TITLE
kak evo ispolzovat, ochen slogno, gde vepak

### ISSUE THREAD

**Issue by idchlife** [ovr/ghubber#1]

**Comment by ovr** [comment]
Chto ti takoe? Kak ti popalo na zemlu?

/b

Just, give me few weeks, I started to develop this :)

**Comment by lex111** [comment]
Вообще хорошее начинание, а в Google Play неактуальная, как я понимаю, версия (скачал его оттуда, глянуть просто)?

@ovr интересует React Native, но ничего на нём не разрабатывал, как можно собрать приложение локально? Это приложение, во многом делается, в качестве обучения, практики?

**Comment by ovr** [comment]
@lex111 Доброго времени суток! 😸 

> Google Play неактуальная

Да, потому что я только начал приложения и быстро его пишу ;)

>  как можно собрать приложение локально

В течении 10 минут напишу гайд в README

@lex111 Какая у тебя платформа?

> Это приложение, во многом делается, в качестве обучения, практики?

У меня второй месяц идет разработки на работе под React-native. Практика не бывает лишней =)

**Comment by lex111** [comment]
@ovr привет, я использую Ubuntu, хочется попробовать посмотреть что из себя представляет React Native, но не знаю с чего начать, может быть порекомендуешь чего?

**Comment by ovr** [comment]
@lex111 Написал для начало - https://github.com/ovr/ghubber#installation

> но не знаю с чего начать, может быть порекомендуешь чего?

Слишком сложный вопрос(

Попробовать собрать этот репозиторий и побаловатся для начало =)

**Comment by lex111** [comment]
@ovr хорошо, спасибо, по инструкции вроде ничего сложного нет (предполагал, что потребуется больше действий сделать, что настроить среду).

**Comment by lex111** [comment]
@ovr привет, это снова я, может быть сможешь помочь? 
Обновил репозиторий, хотел глянуть новые изменения (вчера всё работало), и при запуске `npm run android` такая ошибка:
> The SDK Build Tools revision (23.0.1) is too low for project ':react-native-vector-icons'. Minimum required is 25.0.0

Эмулятор запускал под 23 версией (6 андроид), но обновил виртуальный девайс, чтобы он использовал 7 версию, но всё равно такая же ошибка (в Android Studio тоже 25 версия отмечена). Пытался ещё сбросить кеш, удалил папку node_modules и снова установил все зависимости, но без результата.

**Comment by ovr** [comment]
@lex111 Открой в Android-studio, в левой части найди суб проект `react-native-vector-icons`, в нем будет файл: `build.gradle` а уже внутри него найди строчку buildToolsVersion -> 25.0.2 поставь

По другому я не знаю как пофиксить :)

**Comment by lex111** [comment]
@ovr спасибо, это действительно помогло :clap: 
А вообще такого быть не должно, т.е. это нормальное решение?

**Comment by ovr** [comment]
> А вообще такого быть не должно, т.е. это нормальное решение?

Я не знаю как переопределить buildTools версию для всех суброектов

**Comment by lex111** [comment]
Помогло мне, создал PR https://github.com/ovr/ghubber/pull/2 - или преждевременно?

**Comment by ovr** [comment]
Thank @lex111 for PR, I am going to close this issue 😖 )))))

**Comment by lex111** [comment]
:+1: 
А хотя жаль, не пофлудить больше :smile:

**Comment by ovr** [comment]
@lex111 Если тебе интересно и есть желание сделать PR на какие либо задачи - могу помочь - https://telegram.me/ovrweb

**Comment by lex111** [comment]
@ovr я бы очень хотел поучаствовать, но у меня очень мало знаний React, поэтому пока я вряд ли  могу сделать даже что-то простое. Начну с этой книги https://github.com/survivejs/react-book потом что-нибудь по Native почитаю, и только после этого (если всё это это осилю, скажем так) возможно будут от меня PR :confused:

**Comment by ovr** [comment]
@lex111 Feel free to ask me any questions related my open source project, if you rly want to do cool things in PRs I can help, anyway feel free to contact me inside telegram :3
