### ISSUE TITLE
Login using GitHub OAuth

### ISSUE THREAD

**Issue by lex111** [ovr/ghubber#21]
It seems, it would be nice, considering that this is a GitHub client :smiley:

**Comment by ovr** [comment]
Yeap, sure, this will be, but in `0.6.0` and `OAuth` will be default login 😸

**Comment by lex111** [comment]
Смотрю библиотеку, через которую сейчас происходит авторизация и вижу что есть тип [AuthorizationEntity](https://github.com/SocialConnect/github-sdk-js-flow/blob/master/definitions.js#L10), который требует id и hasked_token, и которые можно получить запросив одну запись авторизации, но сделать это можно только при Basic-аутентификации, не через OAuth (This API can only be accessed with username and password Basic Auth). 

Это я к чему: нашёл такую либу https://github.com/fullstackreact/react-native-oauth может её использовать? Но единственная проблема, что не получится удовлетворять типу AuthorizationEntity: не силен в терминологии, но правильно понимаю, что если ответ не будет содержать все поля, указанные в этом типе, то авторизация не будет работать?

**Comment by ovr** [comment]
@lex111 About OAuth, I am planning to do OAuth by external site, not blank page for mobile
Because I have external api already, for advanced stats

https://ghub.lowl.io/v1/github-user/torvalds/followers-stats
https://ghub.lowl.io/v1/github-user/ovr/followers-stats

https://ghub.lowl.io/v1/github-repository/phalcon/cphalcon/stars-stats

**Comment by lex111** [comment]
Эх, ладно, в пролёте я тогда с PR по OAuth, ок.

**Comment by ovr** [comment]
@lex111 Сорри, просто я еще не решил как делать буду, да и там бекенд код скорее всего придется сделать что бы работало =) Ибо хочу нотификации сделать и возможность включение сборка статистики для пользователей =)

**Comment by lex111** [comment]
@ovr ну всё равно ведь нужно что по клику открывалась ссылка для авторизации или загружать ссылку без перехода в браузер (в WebView на весь экран), тогда я хотел бы помочь

**Comment by ovr** [comment]
Implemented 😃
